// retrieve courses
export const GET_COURSES_REQUEST = "GET_COURSES_REQUEST";
export const GET_COURSES_SUCCESS = "GET_COURSES_SUCCESS";
export const GET_COURSES_FAILURE = "GET_COURSES_FAILURE";

// create course
export const POST_COURSE_REQUEST = "POST_COURSE_REQUEST";
export const POST_COURSE_SUCCESS = "POST_COURSE_SUCCESS";
export const POST_COURSE_FAILURE = "POST_COURSE_FAILURE";

// update course
export const PUT_COURSE_REQUEST = "PUT_COURSE_REQUEST";
export const PUT_COURSE_SUCCESS = "PUT_COURSE_SUCCESS";
export const PUT_COURSE_FAILURE = "PUT_COURSE_FAILURE";
